### ISSUE TITLE
React front end

### ISSUE THREAD

**Issue by cynical89** [GameDevNetwork/gdnsite#26]
We need a basic start to the react front end.

- [ ] A Home page
- [ ] A Vote page similar to [http://gamedevnetwork.org/vote](http://gamedevnetwork.org/vote)
- [ ] A link to the invite link for our discord [http://gamedevnetwork.org/join](http://gamedevnetwork.org/join)
- [ ] A link to the itch.io page for the current jam [http://gamedevnetwork.org/gamejam](http://gamedevnetwork.org/gamejam)

**Comment by ericbastarache** [comment]
A basic home page component is in place; However there's no content on it currently. 
A vote page is roughly in place, however I don't know if it looks good because I got this error when trying to install/run the project: 
```
Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/yarn/0.24.5/libexec/bin/yarn.js:6:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)```

I don't know why that error appears... Nor do I know where that file is; perhaps you know @cynical89 ?
